### ISSUE TITLE
Temp BR Cancel Alarm 

### ISSUE THREAD

**Issue by jokellerweb** [jotomo/AndroidAPS#11]
I got several  "abort TBR" alarm-messages on the combo, with different current TBRs displayed in the Loop and Overview tab.
Screenshot and Logfile here: 
https://www.dropbox.com/sh/21i0qlpqor19lfn/AADNHknoA3J3J7TkL4qYQzvNa?dl=0

**Comment by AdrianLxM** [comment]
I now also got a disconnect and a "TBR cancelled" error.

AndroidAPS accepted this alarm before it made any sound, retried and had success:
[tbrCancelledErrorAccepted.log](https://github.com/jotomo/AndroidAPS/files/1545263/tbrCancelledErrorAccepted.log)

The "my data" history shows what the treatment tab has and corresponds to what the pump should have set :)

**Comment by jokellerweb** [comment]
my AAPS shows TBR with remaining time, combo is after alarm confirmation to 100%. So I get a wrong IOB

**Comment by jokellerweb** [comment]
TBR-Abort-Alarm on Combo repeats after confirming on pump ... 
AAPS TBR remains active
[AndroidAPS_ComboAlert_TBR.log](https://github.com/jotomo/AndroidAPS/files/1545454/AndroidAPS_ComboAlert_TBR.log)

**Comment by AdrianLxM** [comment]
How long did you give the pump time to reconnect to confirm the cancelled TBR? From the video it looks like you did it right away? You can configure the pump that it won't be loud right away.

**Comment by AdrianLxM** [comment]
The mismatch AFTER the error relates to: https://github.com/jotomo/AndroidAPS/issues/12 Storing of the corrected rate does not work.

**Comment by AdrianLxM** [comment]
@jotomo, what is rather "interesting" is, is, that the mismatch seems to be occuring again?

```
de.jotomo.ruffyscripter.commands.CommandException: Failed to set TBR duration, requested: 15, actual: 22
	at de.jotomo.ruffyscripter.commands.SetTbrCommand.verifyDisplayedTbrDuration(SetTbrCommand.java:207) ~[na:0.0]
	at de.jotomo.ruffyscripter.commands.SetTbrCommand.execute(SetTbrCommand.java:78) ~[na:0.0]
	at de.jotomo.ruffyscripter.RuffyScripter.lambda$runCommand$0$RuffyScripter(RuffyScripter.java:259) ~[na:0.0]
	at de.jotomo.ruffyscripter.RuffyScripter$$Lambda$0.run(Unknown Source) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
```

@jokellerweb, what phone do you have?

**Comment by jokellerweb** [comment]
I ran the alarm about 1 minute, he did not stop.

My phone: Samsung Galaxy S5

**Comment by jotomo** [comment]
Please check a few things:
* Via actions set a TBR of 200% for 60m to see if setting a TBR works in general
* Note the production year on the back of the pump
* Check firmware version (briefly displayed after inserting a battery, something like SW 1.06)

* Disable the loop (or disable bluetooth on the pump) and manualy do:
* Set a TBR of 130% for 30m
* Wait a few minutes
* Go into TBR menu again, the duration should now be displayed as something like 0:28
* Press down and note what the pump does, it should jump to 0:15.
* Try pressing up down some more, does anything happen pressing down when 0:15 is displayed, are there any input lacks when pressing up/down multiple times (single presses, don't keep the button pressed continuously)?

**Comment by jokellerweb** [comment]
- TBR works in general... there were many successful TBRs without alarm

- Production year: 2015

- Firmware V1.07

Disable the loop (or disable bluetooth on the pump) and manualy 

- do: no chance to set time under 30 min. Up to 60 min is no problem, down to 30 min is possible too. but not under 30 min...
Video: https://www.dropbox.com/s/fqinu9zopbioyf7/TBR_bug.mp4?dl=0

**Comment by jotomo** [comment]
Thanks, I think I missed to document a step in the configuration. The step-size can be configured via the 360 configuration software, it' needs to be set to 15 min.

**Comment by jokellerweb** [comment]
ok, thanks... I test it...

**Comment by jokellerweb** [comment]
scheint jetzt zu laufen, keine Fehlermeldungen mehr...

**Comment by jokellerweb** [comment]
Error messages are significantly reduced, but not completely disappeared.

 
- 17:39-18:09  240% (AAPS)

- 18:09 "TBR Abbruch" (Combo)

- 18:10-18:40 0% (AAPS)

**Comment by AdrianLxM** [comment]
This looks like the corner case where the TBR of 240% runs out (after 30 minutes) when the new TBR is set and the scripter is in the TBR menus @jotomo

**Comment by jotomo** [comment]
@jokellerweb Did you confirm the alert or did you let it ring?

**Comment by jokellerweb** [comment]
I confirmed the alert

**Comment by jotomo** [comment]
AAPS would've confirmed it: https://github.com/jotomo/AndroidAPS/blame/combo-scripter-v2/README-Combo.md#L88

Please provide logs  covering 17:30 to 18:10.

**Comment by jokellerweb** [comment]
here the complete log: 
https://www.dropbox.com/sh/21i0qlpqor19lfn/AADNHknoA3J3J7TkL4qYQzvNa?dl=0

or 17:30 to 18:13
[log_1730-1813.log](https://github.com/jotomo/AndroidAPS/files/1545969/log_1730-1813.log)

**Comment by jokellerweb** [comment]
new "TBR-Abbruch"-Alarm on Combo, 17:26  at the end of a 15 minute tbr

![2017-12-11 17 30 22](https://user-images.githubusercontent.com/31852218/33842435-d372d9b4-de9a-11e7-902e-23b59b49a4b8.jpg)

[Uploading AndroidAPS_ComboAlert_TBR_2017-12-11.log…]()
