### ISSUE TITLE
Example of TBR cancelled alarm

### ISSUE THREAD

**Issue by AdrianLxM** [jotomo/AndroidAPS#15]
TBR was cancelled. It was cancelled automatically before it became really loud (awake in a silent room noticable, bit not annoying, would not wake anyone).

timestamp of exception: 01:56:26.278
Cause was a disconnect: 01:56:26.104

Before that from 01:56:20.981 to 01:56:26.089, so for about 5 seconds it was in state "Waiting for pump to process scrolling input for percentage, current: 100, desired: 0, scrolling down".

This time the pump was directly next to the phone. This phenomenon is rather a small annoyance  but not a dealbreaker that would prevent the setup to be used for looping.

**Comment by jotomo** [comment]
Pump not responding anymore than raising a TBR CANCELLED alarm sounds like setting a TBR within the last minute of a previous TBR. Should be fixed via #17.
