### ISSUE TITLE
Low cartridge alarm does not raise a wear notification

### ISSUE THREAD

**Issue by ceben80** [jotomo/AndroidAPS#16]
Low cartridge alarm during a bolus is raised and shown in AAPS but not on smartwatch (13.12.17 around 8.30 am)

[AndroidAPS.log](https://github.com/jotomo/AndroidAPS/files/1554498/AndroidAPS.log)

**Comment by jotomo** [comment]
@AdrianLxM Notifications on watch now require the pref _Use system notification ..._ to be enabled, no?

**Comment by AdrianLxM** [comment]
Dedicated wear notifications no longer exist.
Android wear will show the system notifications. This way you don't have to dismiss them on two devices.

**Comment by jotomo** [comment]
@AdrianLxM Thanks
@ceben80 Enable the above option and you're good to go.

**Comment by ceben80** [comment]
thanks, enabled it
