### ISSUE TITLE
Dana-Pump active after App-Crash

### ISSUE THREAD

**Issue by jokellerweb** [jotomo/AndroidAPS#21]
when updating the BR in the "Local Profile" the app has crashed. Then the Dana pump was active 

crash-time: 12-15 10:58 

![screenshot_20171215-112228 1](https://user-images.githubusercontent.com/31852218/34043243-704dcb42-e1a0-11e7-8a7b-e8393f140ff0.png)

[catlog.txt](https://github.com/jotomo/AndroidAPS/files/1562707/catlog.txt)
[afterAPP-Bug.log](https://github.com/jotomo/AndroidAPS/files/1562709/afterAPP-Bug.log)
[beforeAPP-Bug.log](https://github.com/jotomo/AndroidAPS/files/1562714/beforeAPP-Bug.log)

**Comment by AdrianLxM** [comment]
This is rather a bug in AAPS not in the combo driver. Could you please open an issue in the main repo?
