### ISSUE TITLE
combo disconnection alarm not on wear

### ISSUE THREAD

**Issue by jokellerweb** [jotomo/AndroidAPS#25]
my combo was disconnected for 34 minutes. Alarm appeared on phone but not on the watch.

**Comment by AdrianLxM** [comment]
@jokellerweb, do you have "Use system notifications for alerts..." activated in the settings?

**Comment by jokellerweb** [comment]
I think it was a bluetooth crash on my phone. Watch and combo lost the connection, only after a phone restart everything was connected again
