### ISSUE TITLE
empty alert window after "failed to update profile"

### ISSUE THREAD

**Issue by jokellerweb** [jotomo/AndroidAPS#29]
"pump not reachable"-alarm at profile switch (BR 85% for 8 hours). urgent alarm on watch and phone, that's ok. But
![screenshot_20171221-221618](https://user-images.githubusercontent.com/31852218/34275933-9c218aa2-e69f-11e7-9a67-be7fc130ca2d.png)
 in the AAPS, an alert window was opened without text.

**Comment by jotomo** [comment]
@jokellerweb Thanks for reporting, fixed now.
