### ISSUE TITLE
Cancelling a bolus while it is still in "programming pump for bolusing" reads old history datum

### ISSUE THREAD

**Issue by AdrianLxM** [jotomo/AndroidAPS#3]
Reproduce:

Step 1: Deliver a bolus of 0.7 units. Wait a couple of minutes
Step 2: Trigger a bolus of 8 Units
Step 3: Wait 10 seconds after "programming pump for bolusing" appears and press "stop bolus".
Result: The treatments plugin now has two entries with 0.7 units. Once at the original time; once when the second bolus was cancelled.

**Comment by AdrianLxM** [comment]
Corresponding logs:
from:
`12:56:22.943 [class info.nightscout.androidaps.queue.QueueThread] DEBUG [info.nightscout.androidaps.db.DatabaseHelper:590]: TREATMENT: New record from: USER Treatment{date= 1512680141000, date= 12/7/17 12:55 PM, isValid= true, isSMB= false, _id= null, pumpId= 0, insulin= 0.7, carbs= 0.0, mealBolus= false}`
...
to:
`12:49:24.619 [class info.nightscout.androidaps.queue.QueueThread] DEBUG [info.nightscout.androidaps.db.DatabaseHelper:590]: TREATMENT: New record from: USER Treatment{date= 1512679764000, date= 12/7/17 12:49 PM, isValid= true, isSMB= false, _id= null, pumpId= 0, insulin= 0.7, carbs= 0.0, mealBolus= false}`
[AndroidAPS.log](https://github.com/jotomo/AndroidAPS/files/1540577/AndroidAPS.log)

![screenshot_20171207-130341](https://user-images.githubusercontent.com/9692866/33738729-8b8b3d10-db9a-11e7-936e-4c3b61cb6bd7.png)

**Comment by jotomo** [comment]
Fixed via #4
