### ISSUE TITLE
bolus cancellation likely broken with SMB

### ISSUE THREAD

**Issue by jotomo** [jotomo/AndroidAPS#34]
if an SMB is running in the background, a new bolus is requested and then attempted to cancel: this will likely cancel the SMB and then run the bolus.

**Comment by AdrianLxM** [comment]
How about solving this on a higher level upstream? This most likely will affect the other pump models that read history (Dana Rv2, Dana RS) or probably even all pumps to some extent.

My idea would be: on a bolus cancel always clear the CommandQueue of any bolus types (SMB or standard).
 * If a standard bolus is delivered and cancelled, an SMB should not follow anyways as a new evaluation of the situation will be done afterwards with the new IOB reality.
 * If an SMB is delivered and cancelled (no problem if one is missing as they are micro), the user actually would want to cancel the manually triggered one -> delete it from the queue.

**Comment by jotomo** [comment]
> How about solving this on a higher level upstream? 

Yes. I just quickly dumped it here to not forget about it and check how combo-specific this is, while I continued on another task.

Cancelling all running and queued boluses sounds reasonable and is simple to argue about 👍

**Comment by jotomo** [comment]
Moved upstream.
