### ISSUE TITLE
wrong alert message pump time out of range

### ISSUE THREAD

**Issue by jokellerweb** [jotomo/AndroidAPS#35]
in the German Version,  Notification received at midnight: "Bitte aktualisieren Sie die Uhr auf der Pumpe". 
[AndroidAPS (1).log](https://github.com/jotomo/AndroidAPS/files/1594746/AndroidAPS.1.log)
pump time and phone time were exactly the same.

**Comment by jotomo** [comment]
@jokellerweb Thanks for reporting, the issue is fixed and tested.
