### ISSUE TITLE
COB not calculated at times

### ISSUE THREAD

**Issue by savek-cc** [jotomo/AndroidAPS#36]
Current v2 branch, entered carbs via wizzard. 30min later, COB is not shown on main screen and not active in wizzard.

**Comment by savek-cc** [comment]
![screenshot_20171230-213634](https://user-images.githubusercontent.com/13501427/34457202-1f303482-edaa-11e7-8224-f47982eb0ffd.png)
![screenshot_20171230-213620](https://user-images.githubusercontent.com/13501427/34457203-27aa947c-edaa-11e7-8dc1-68bbb833284b.png)

**Comment by savek-cc** [comment]
@AdrianLxM clean repo without your patch.

**Comment by AdrianLxM** [comment]
Can you please make sure that you really have 8c213cbc117346e03a63748edc419b49c0a9996c in that @MilosKozak merged about two hours ago.

**Comment by savek-cc** [comment]
Commit ID in about is 220554db.

**Comment by jotomo** [comment]
Issue was introduced by https://github.com/jotomo/AndroidAPS/commit/f968ec630c8993442812fbbe8b41815f1c02fe53. Fix is not working for me either, I've locally reverted the commit for the time being, which restores COB display.

**Comment by gregorybel** [comment]
Issue is quiet old, I see it on 1.5h too. 
Could it be related to nightscout?
I have since a few days NS issues (mongodb moving their servers) where lots of local entries are lost.

**Comment by jotomo** [comment]
This has been resolved for me with Milo's patch that was merged here: https://github.com/jotomo/AndroidAPS/commit/cbf005a11e84875458a951ab90457eb5e42c0162
How's your experience @savek-cc @ceben80 @gregorybel 
@gregorybel The issue in 1.5h was another bug I think. This is unrelated to Nightscout.

**Comment by jotomo** [comment]
Fixed upstream, create a new issue upstream if this occurs again.
