### ISSUE TITLE
Set time/date automatically once ruffy supports the menu

### ISSUE THREAD

**Issue by jotomo** [jotomo/AndroidAPS#47]

**Comment by gregorybel** [comment]
what needs to be done on Ruffy?

**Comment by jotomo** [comment]
The menus aren't parsed by ruffy yet.

**Comment by gregorybel** [comment]
means we need to parse 1440 possibilities or is there a cleverer way?

**Comment by jotomo** [comment]
The _Time and date settings_ menu has a couple of submenus for hour, minute, year, month, day etc with a corresponding title. Classes like `MenuFactory`, `TitleResolver` etc need to be extended to tokenize the menus properly, not compare the entire screen.
