### ISSUE TITLE
After manually pressing "refresh" connection to pump does not get released

### ISSUE THREAD

**Issue by AdrianLxM** [jotomo/AndroidAPS#8]
On https://github.com/jotomo/AndroidAPS/pull/6/commits/588cfcf1a173d3892a415b3ac1804bb250bf19a3 but also https://github.com/jotomo/AndroidAPS/pull/5 and https://github.com/jotomo/AndroidAPS/pull/4 merged.

Reproduce:
1) Manually press "refresh" in the combo tab.
2) Wait until the "Activity:" row is gets emtpied
-> Combo still shows bluetooth symbol for a longer period of time

Screenshot (while combo still has BT symbol active):
![screenshot_20171208-103806](https://user-images.githubusercontent.com/9692866/33780025-7daa6d96-dc4f-11e7-9945-60bb67706a20.png)

Log:
[AndroidAPS.log](https://github.com/jotomo/AndroidAPS/files/1543529/AndroidAPS.log)

**Comment by AdrianLxM** [comment]
The same seems to happen when long-pressing "TDDS"

**Comment by jotomo** [comment]
Indeed, those actions don't using the queue so they need to manually close the connection, or just the queue.

**Comment by jotomo** [comment]
Fixed via #6
